# Generated by Django 3.2.21 on 2023-09-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('profiles', '0002_rename_profiles_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reviewed',
            field=models.ManyToManyField(blank=True, related_name='reviewed', to='review.Post'),
        ),
    ]
