# Generated by Django 3.2.21 on 2023-09-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reviewed',
        ),
    ]
