# Generated by Django 3.2.21 on 2023-09-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
