# Generated by Django 3.2.21 on 2023-09-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20230923_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
