# Generated by Django 3.2.21 on 2023-09-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20230927_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
