# Generated by Django 3.2.21 on 2023-09-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_on',)},
        ),
    ]
